---
# tasks file for roles/Installing_Package_Ubuntu

  - name: Installing [-Java-]
    apt:
      name: default-jre
      state: latest
      update_cache: yes

  - name: Installing [-boto,ansible, and openstack-]
    pip:
      name:
         - boto
         - ansible
         - python-openstackclient
