---
# tasks file for roles/Nagios_main_Ubuntu
- name: Download and Extracting Nagios Core
  unarchive:
    src: https://assets.nagios.com/downloads/nagioscore/releases/nagios-4.4.5.tar.gz
    dest: /tmp
    copy: no

- name: Configure Nagios within ubuntu
  command: ./configure --with-nagios-group=nagcmd --with-command-group=nagcmd --with-httpd_conf=/etc/apache2/sites-enabled
  args:
    chdir: /tmp/nagios-4.4.5


- name: Compile Nagios make clean
  make:
    chdir: /tmp/nagios-4.4.5
    target: clean

- name: Compile Nagios make all
  make:
    target: all
    chdir: /tmp/nagios-4.4.5

- name: Compile Nagios make install
  make:
    target: install
    chdir: /tmp/nagios-4.4.5

- name: Compile Nagios make install-init
  make:
    target: install-init
    chdir: /tmp/nagios-4.4.5

- name: Compile Nagios make install-config
  make:
    target: install-config
    chdir: /tmp/nagios-4.4.5

- name: Compile nagios and make install-commandmode
  make:
    target: install-commandmode
    chdir: /tmp/nagios-4.4.5

- name: Fire up the web Interface Installer
  make:
    target: install-webconf
    chdir: /tmp/nagios-4.4.5

- name: Add user account
  htpasswd:
    path: /usr/local/nagios/etc/htpasswd.users
    name: user
    password: password

- name: a2enmod cgi
  command: a2enmod cgi

- name: Restarting Apache2
  service:
    name: apache2
    state: restarted

