---
# tasks file for roles/Nagios_plugins_Centos
- name: Downloading and Extracting Nagios Plugins
  unarchive:
    src: https://nagios-plugins.org/download/nagios-plugins-2.2.1.tar.gz
    dest: /tmp
    remote_src: yes

- name: Configure Nagios Plugins
  command: ./configure --with-nagios-user=nagios --with-nagios-group=nagiosxi
  args:
    chdir: /tmp/nagios-plugins-2.2.1

- name: Using make
  make:
    chdir: /tmp/nagios-plugins-2.2.1

- name: Use make install
  make:
    target: install
    chdir: /tmp/nagios-plugins-2.2.1

- name: Starting and Enabling Nagios
  service:
    name: nagios
    state: started
    enabled: yes

