---
# tasks file for roles/Elastic_for_Centos
- name: Install pre-requisite of elastic
  yum:
    name: java-11-openjdk-devel
    state: latest
    update_cache: yes

- name: Install elasticsearch repository
  yum_repository:
    name: Elastic_7.X_repo
    baseurl: https://artifacts.elastic.co/packages/7.x/yum
    gpgcheck: yes
    gpgkey: https://artifacts.elastic.co/GPG-KEY-elasticsearch
    enabled: yes
    description: Elastic 7.x repo

- name: Install Elasticsearch gpg key
  rpm_key:
    key: https://artifacts.elastic.co/GPG-KEY-elasticsearch
    state: present

- name: Install Elasticsearch
  yum:
    name: elasticsearch
    state: present
    update_cache: yes

- name: Update config file to allow access
  lineinfile:
    destfile: /etc/elasticsearch/elasticsearch.yml
    regexp: '#network.host:'
    line: 'network.host: localhost'

- name: Update config to allow access
  lineinfile:
    destfile: /etc/elasticsearch/elasticsearch.yml
    regexp: '#http.port:'
    line: 'http.port: 9200'

- name: Update time
  lineinfile:
    dest: /usr/lib/systemd/system/elasticsearch.service
    regexp: 'TimeoutStartSec='
    line: 'TimeoutStartSec=900'

- name: Enable and start elasticsearch
  service:
    name: elasticsearch
    state: started
    enabled: yes

- name: Install logstash repo
  yum_repository:
    name: Elastic repository for 7.x packages
    baseurl: https://artifacts.elastic.co/packages/7.x/yum
    gpgcheck: yes
    gpgkey: https://artifacts.elastic.co/GPG-KEY-elasticsearch
    enabled: yes
    description: Elastic 7.x packages repo

- name: Install Logstash
  yum:
    name: logstash
    state: present
    update_cache: yes

- name: Update config file
  lineinfile:
      dest: /etc/logstash/logstash.yml
      regexp: 'http.host:'
      line: 'http.host: 127.0.0.1'

- name: Start and Enable Logstash
  service:
    name: logstash
    state: started
    enabled: yes

- name: Install kibana repo
  yum_repository:
    name: Kibana 7.x packages
    baseurl: https://artifacts.elastic.co/packages/7.x/yum
    gpgcheck: yes
    gpgkey: https://artifacts.elastic.co/GPG-KEY-elasticsearch
    enabled: yes
    description: Kibana-7.x

- name: Install Kibana
  yum:
    name: kibana
    state: present
    update_cache: yes

- name: Update config server.host
  lineinfile:
    destfile: /etc/kibana/kibana.yml
    regexp: 'server.host'
    line: 'server.host: 0.0.0.0'

- name: Update config file server.port
  lineinfile:
    dest: /etc/kibana/kibana.yml
    regexp: 'server.port:'
    line: 'server.port: 5601'

- name: Enable and start kibana
  service:
    name: kibana
    state: started
    enabled: yes

