---
# tasks file for roles/Nagios_main_Centos
- name: Downloading and Extracting Nagios from official website
  unarchive:
    src: https://assets.nagios.com/downloads/nagioscore/releases/nagios-4.4.5.tar.gz
    dest: /tmp
    remote_src: yes

- name: Configure Nagios on Centos
  command: ./configure --with-command-group=nagiosxi
  args:
    chdir: /tmp/nagios-4.4.5

- name: Configuring and make clean
  make:
    target: clean
    chdir: /tmp/nagios-4.4.5

- name: Configure make all
  make:
    target: all
    chdir: /tmp/nagios-4.4.5

- name: Configure make install
  make:
    target: install
    chdir: /tmp/nagios-4.4.5

- name: Configure make install-init
  make:
    target: install-init
    chdir: /tmp/nagios-4.4.5

- name: Configure make install-daemoninit
  make:
    target: install-daemoninit
    chdir: /tmp/nagios-4.4.5

- name: Configure make install-config
  make:
    target: install-config
    chdir: /tmp/nagios-4.4.5

- name: Configure make install-commandmode
  make:
    target: install-commandmode
    chdir: /tmp/nagios-4.4.5

- name: Configure make install-exfoliation
  make:
    target: install-exfoliation
    chdir: /tmp/nagios-4.4.5

- name: Install webconf
  make:
    target: install-webconf
    chdir: /tmp/nagios-4.4.5

- name: install passlib
  pip:
    name: passlib

- name: Create usert to authenticate
  htpasswd:
    path: /usr/local/nagios/etc/htpasswd.users
    name: user
    password: password

- name: Restart httpd
  service:
    name: httpd
    state: restarted
    enabled: yes

