---
# tasks file for roles/Configure_for_Centos

- name: Install latest httpd, mariadb-server php-mysqlnd php-fpm
  dnf:
    name:
      - httpd
      - mariadb-server
      - php-mysqlnd
      - php-fpm
    update_cache: yes

- name: Enable and start httpd
  service:
    name: httpd
    enabled: yes
    state: started

- name: Enable and start httpd
  service:
    name: mariadb
    enabled: yes
    state: started

- name: Install Required packages
  dnf:
    name:
      - gcc
      - glibc
      - glibc-common
      - wget
      - gd
      - gd-devel
      - perl
      - postfix

- name: Add group nagiosxi
  group:
    name: nagiosxi
    state: present

- name: Create Nagios user account
  user:
    name: nagios
    group: nagiosxi

