---
# tasks file for roles/Nagios_plugins_Ubuntu
- name: Installing Nagios Plugins
  unarchive:
    src: https://nagios-plugins.org/download/nagios-plugins-2.3.3.tar.gz
    dest: /tmp
    remote_src: yes

- name: Configure Nagios Plugins
  command: ./configure --with-nagios-user=nagios --with-nagios-group=nagcmd
  args:
    chdir: /tmp/nagios-plugins-2.3.3

- name: Configure using make
  make:
    chdir: /tmp/nagios-plugins-2.3.3

- name: Configure using make install
  make:
    target: install
    chdir: /tmp/nagios-plugins-2.3.3

- name: Enable and Start Nagios
  service:
    name: nagios
    enabled: yes
    state: started
