---
# tasks file for roles/Installation_for_Ubuntu
- name: Installing dhcpd
  apt:
    name: isc-dhcp-server
    state: latest
    update_cache: yes

- name: Installing bind9
  apt:
    name: bind9
    state: latest
    update_cache: yes

- name: Installing vsftpd
  apt:
    name: vsftpd
    state: latest
    update_cache: yes

- name: Installing samba
  apt:
    name: samba
    state: latest
    update_cache: yes

- name: Installing httpd
  apt:
    name: apache2
    state: latest
    update_cache: yes

- name: Installing mariadb
  apt:
    name: mariadb-server-10.3
    state: latest
    update_cache: yes

